### ISSUE TITLE
Can I open a project without a file in it?

### ISSUE THREAD

**Issue by mosheavni** [nvim-telescope/telescope-project.nvim#100]
When I choose a project by hitting `<CR>` I'd like the project to just open on a blank file with the cwd of the project instead of having to choose a file.
How can I do that?
Thanks.

**Comment by AntoscencoVladimir** [comment]
Hello you have to create a project **(in select project popup)** by <C-a> and then choose the project by <C-l>

**Comment by alerque** [comment]
I believe this issue can be closed. Opening a project without opening a file can be done with <kbd>Ctrl</kbd>+<kbd>l</kbd>. The README has info on how to change the bindings for this.
