### ISSUE TITLE
Change directory of terminal

### ISSUE THREAD

**Issue by calvinchoy** [nvim-telescope/telescope-project.nvim#109]
Hi,

Does anyone know whether it is possible to change the terminal current directory when changing project? For example when I am in project A and switch to project B, exit neovim. Terminal should be in project B folder.

Thanks!

**Comment by AntoscencoVladimir** [comment]
Hello @calvinchoy, in what see there is no such functionality, it only change the current dir of vim shell. To do what you need the plugin should interact with terminal where you running vim thought.

**Comment by calvinchoy** [comment]
Thanks Vladimir,

I am using the kitty terminal, I will try to use autocommands in neovim to interact with the terminal.

**Comment by AntoscencoVladimir** [comment]
@calvinchoy I using kitty too + zsh, I'm not sure about kitty terminal itself even there are sessions feature in it, most likely it related to bash or zsh (in my case).
When project changed we need tell to bash that we changed directory somehow from vim, like last-workindg-dir plugin from oh-my-zsh in that case it write directory path in file and then read it from there on each new instance of opened terminal window.
When we change project in vim it should do something like put vim in background job then change directory in terminal (bash) and then restore vim. Maybe there is a way to change current terminal 
 directory directly, anyway for that need to add changes to the plugin if need to do it automatically on project change. Anyway seems that doesn't have to much sense thought, but can be additional feature (if it possible to do).

**Comment by calvinchoy** [comment]
I agree with you that this shouldn’t be the plugin responsibility. So this issue can be closed.

For my specific scenario I want the tab title of kitty to reflect the current working directory. I think this can be achieved by autocommands and using kitty @ set-tab-title command.
