### ISSUE TITLE
Disable nvimtree and file browser on project switch

### ISSUE THREAD

**Issue by calvinchoy** [nvim-telescope/telescope-project.nvim#116]
Currently when I switch to another project, nvim-tree and the telescope file browser is being shown automatically. 

Is it possible to disable this behavior?

**Comment by AntoscencoVladimir** [comment]
@calvinchoy why? The idea was to switch project also in `nvim-tree` to simulate kinda another text editors functionality. Can you explain what exactly do you expect when switch project?

**Comment by calvinchoy** [comment]
@AntoscencoVladimir well I guess it is more of a preference thing. I totally understand that some people want to have the nvim-tree and telescope visible when they switch the project.

In my case for example I find it unnecessary to toggle on nvim-tree visible if I have hidden for example, so switching a new project I have to hide the nvim-tree again. Also the telescope file picker is also open at the same time, which I find it a bit overload. 

As switching a project is something I do manually and thus aware of the action I personal don't need have the nvim-tree toggled on + telescope file picker shown. I am not sure how much work it is, but maybe it is an idea to add a configuration optional setting that by default is on but can be set false if preferred. At the and I just want to know that the project is switched succesfully.

Currently what I can achieve partially using autocommands is, on DirChange:
- set my kitty tab title corresponding to the switched project directory name
- clear/close/new buffer from previous project
- Hide nvim-tree
- use vim-notify to notify using popup that the project is switched successfully to the project

**Comment by AntoscencoVladimir** [comment]
@calvinchoy ok, clear I will do that optional (if my PR will be merged) and also will check vim notify

**Comment by AntoscencoVladimir** [comment]
@calvinchoy here it is https://github.com/nvim-telescope/telescope-project.nvim/pull/117 by default **false**

**Comment by calvinchoy** [comment]
Thanks a lot, works great!
