### ISSUE TITLE
Add ability to change default action

### ISSUE THREAD

**Issue by zwhitchcox** [nvim-telescope/telescope-project.nvim#119]
It would be good if I could change the default action to `change_working_directory()` or an arbitrary function that I give it. I really don't want the file picker ever, because I'd rather just see the `nvim-tree`, because it lets me familiarize myself with the directory structure, and also I'd like it to open the most recent session.

Also, the keyboard shortcuts don't work, because telescope makes `C-l` `complete_tag`, and this plugin doesn't override it. I know this is an unrelated issue, but if I could just set the default action, I wouldn't have to worry about that, and I will never want the fzf file browser, so that's not a problem.

It seems like this would be extremely easy just by setting [`on_project_selected`](https://github.com/nvim-telescope/telescope-project.nvim/blob/master/lua/telescope/_extensions/project/main.lua#L85-L88) to the options the user passes in:

```lua
      local on_project_selected = function()
        _actions.find_project_files(prompt_bufnr, hidden_files)
      end
      actions.select_default:replace(setup_config.on_project_selected or on_project_selected)
```

**Comment by gerryhernandez** [comment]
I want this, too. I threw together a PR (#121) and could use feedback and help with testing. Quick copy/paste for anyone who's willing to help (assuming you're using Packer for package management):

```
use({ "gerryhernandez/telescope-project.nvim", branch = "configureDefaultAction" })
```
Thanks!

**Comment by alexander-born** [comment]
No PR is necessary to achieve this. See this [comment](https://github.com/nvim-telescope/telescope-project.nvim/issues/84#issuecomment-1080355030).

.`/lua/config/telescope.lua`
```lua
local telescope = require'telescope'

local function on_project_selected(prompt_bufnr)
    local project_actions = require'telescope._extensions.project.actions'
    local user_actions_available, user_project_actions = pcall(require, 'user.project.actions')
    project_actions.change_working_directory(prompt_bufnr, false)
    vim.g.project_path = vim.fn.getcwd()
    if user_actions_available then user_project_actions(prompt_bufnr) end
end

local M = {}

function M.project()
    telescope.extensions.project.project{
        display_type = 'full',
        attach_mappings = function(prompt_bufnr, map)
            map({'n', 'i'}, '<CR>', on_project_selected)
            return true
        end,
    }
end

return M
```
And then just map this like this:
```lua
local mytelescope = require'config.telescope'
vim.keymap.set('n', '<leader>fp',  mytelescope.project, {desc = "Find Project"})

**Comment by zhaogangang** [comment]
i test with telescope-frecency.nvim, it's will be error just like 

``` lua    
require("telescope").extensions.project.project {
        display_type = 'two-segment',
        attach_mappings = function(prompt_bufnr, map)
            map('i', '<cr>', function()
                require("telescope._extensions.project.actions").
                    change_working_directory(prompt_bufnr, false)

                require('telescope').extensions.frecency.frecency({ workspace = 'CWD' })
            end)
            return true
        end,
    }
```

**Comment by zhaogangang** [comment]
i am found the error and resolve it, but i still think PR (https://github.com/nvim-telescope/telescope-project.nvim/pull/121) is necessary, for lots people
