### ISSUE TITLE
What is `w0` in the projects list?

### ISSUE THREAD

**Issue by tqwewe** [nvim-telescope/telescope-project.nvim#129]
![image](https://user-images.githubusercontent.com/16362377/227470269-30f25904-c135-4ad6-a41d-c185d6421f71.png)

I have added some projects, but each project has `w0` label after it. What does this mean and how could I get rid of it?

**Comment by claidler** [comment]
It's the beginnings of a workspace feature. It defaults to w0. Workspace 0. I can't remember exactly where it got to, to be honest

**Comment by liiil825** [comment]
I have the same problem, how to delete

**Comment by sullrich84** [comment]
Same question here
