### ISSUE TITLE
[Feature Request] Run local `exrc` file when switching to a project

### ISSUE THREAD

**Issue by Aman9das** [nvim-telescope/telescope-project.nvim#145]
As specified in [https://neovim.io/doc/user/options.html#'exrc'](https://neovim.io/doc/user/options.html#'exrc') and https://neovim.io/doc/user/starting.html#exrc, the `exrc` type files in the current directory should be run when switching to it.

These `exrc` files specify project specific configurations, and should be loaded when opening the project.

**Comment by scippio** [comment]
What about use "on_project_selected"?
