### ISSUE TITLE
Ability to list parent directories as a way to add projects?

### ISSUE THREAD

**Issue by hahuang65** [nvim-telescope/telescope-project.nvim#15]
I've been looking for a way to declare a list of directories that contain my projects so that telescope-project can add all (git-enabled) subdirectories, instead of manually needing to add all projects?

Is there any way to do this?

**Comment by claidler** [comment]
Not currently @hahuang65 but I'll add this to the roadmap

**Comment by Conni2461** [comment]
How about utilizing `Telescope file_browser` and `telescope-project` is able to inject a mapping in this builtin.

Interface doesn't exist yet but i thought about enabling extensions to inject mappings for a while now.
