### ISSUE TITLE
Add 'neovim-plugin' as topic to the GitHub repository

### ISSUE THREAD

**Issue by Frestein** [nvim-telescope/telescope-project.nvim#159]
I would like to request the addition of the 'neovim-plugin' tag to this repository. This tag is necessary for the plugin to be listed on [dotfyle.com](https://dotfyle.com/), which is a valuable resource for Neovim users.

Please consider tagging the repository accordingly.

![image](https://github.com/user-attachments/assets/7a8af576-9182-4110-a6e8-adfdc2c913c7)

**Comment by claidler** [comment]
I've made this change. Please notify if there's any problems

**Comment by Frestein** [comment]
> I've made this change. Please notify if there's any problems

Thank you!
https://dotfyle.com/plugins/nvim-telescope/telescope-project.nvim
