### ISSUE TITLE
VSCode-like session management

### ISSUE THREAD

**Issue by Shatur95** [nvim-telescope/telescope-project.nvim#16]
I would like to suggest a more advanced way of managing sessions.

Instead of displaying a list of files from a session, it would be more convenient to immediately open the last state of the session and automatically save this state on exit. The states for each session could be `.vim` or `.lua` files that contains commands to execute and stored in a user-specified folder.

What do you think about it?

**Comment by claidler** [comment]
@Shatur95 I use https://github.com/tpope/vim-obsession for this purpose. I'm not sure if what your asking would be considered outside the scope as an extension of telescope. How would you expect it to work?

**Comment by Shatur95** [comment]
vim-obsession is a great plugin, but I can't switch between sessions using Telescope.
This plugin is also awesome, but it does not allow loading the session state, only allows switching between files.

So, I suggesting a slightly different behavior. It would be much more convenient to load the session immediately instead of selecting files. I would imagine that it works like vim-obession, but with the ability to select a session using Telescope.
Perhaps you are right, this can be considered as out of scope for this plugin and will require a complete redesign of the plugin. But I still think it's a good idea.

**Comment by claidler** [comment]
I think it's a really good idea @Shatur95 and a useful feature. Also something I've considered previously. I just need to figure out how exactly to implement it, and if it will be simple enough to be useful within the scope of a telescope plugin. Maybe something like pressing 's' on a project in project selection loads a project session. But then, do I also allow users to create sessions, and do I automatically update the session files, how vim-obsession does. I guess ideally the answer would be yes to both of those. I think I need to do this.

**Comment by Shatur95** [comment]
> Maybe something like pressing 's' on a project in project selection loads a project session.

I would suggest to do it on `<CR>` and show list of the files on `f`.

> But then, do I also allow users to create sessions, and do I automatically update the session files, how vim-obsession does. I guess ideally the answer would be yes to both of those. I think I need to do this.

It would be awesome.

**Comment by claidler** [comment]
> I would suggest to do it on `<CR>` and show list of the files on `f`.
I think default behaviour for <CR> should be file selection still, as telescope is ultimately a plugin for searching files, however I'll add the ability to customise it in their config to allow it to be used for sessions.

**Comment by Shatur95** [comment]
> I think default behaviour for <CR> should be file selection still, as telescope is ultimately a plugin for searching files, however I'll add the ability to customise it in the users config to allow it to be used for sessions.

I would say that Telescope is a general-purpose picker, not only for files. And in this case, it allows you to select sessions. Typically Telescope does not allow you to select something twice. But if it can be customized, it will be great :)

**Comment by Shatur95** [comment]
I decided to wrote [a separate plugin](https://github.com/Shatur95/neovim-session-manager) for this purpose.

**Comment by claidler** [comment]
@Shatur95 No probs. Feel free to put in a PR if you want to add it here also.

**Comment by venzen** [comment]
> Personally i want to switch to a project and just see the latest session that i was working on.

Second this notion. Having the ability to define projects is great. Yet, once the directory location and files are reinstated, the session state of the last time I worked on that project is the logical next step.
