### ISSUE TITLE
error in creating project title for projects not having git 

### ISSUE THREAD

**Issue by adgai19** [nvim-telescope/telescope-project.nvim#17]
Hi, while creating projects, I encountered a bug. 
While creating a new project, the project name as 
`fatal: not a git repository (or any of the parent directories): .git`
And as a result I am not able to switch to the project.
I am running neovim nightly on ubuntu 20.10

**Comment by zetashift** [comment]
I have the same thing! I have a project that it's just a folder with a bunch of markdown files in it:

![image](https://user-images.githubusercontent.com/1857826/114222305-b3631700-996e-11eb-8cf5-c21be6a03522.png)

**Comment by claidler** [comment]
Looking into this now

**Comment by claidler** [comment]
Should be resolved now. Thanks for letting me know, and thanks @adgai19 for providing a quick fix. Hopefully not, but if for whatever reason you need to update your project dirs manually you can do so at `~/.local/share/nvim/telescope-projects.txt`. I'll close this for now.

**Comment by zetashift** [comment]
Thanks @adgai19 for the fix and @claidler for the amazing extension! It works now.
