### ISSUE TITLE
Show project full path, and project renamings

### ISSUE THREAD

**Issue by artofnothingness** [nvim-telescope/telescope-project.nvim#24]
It would be cool to see not only top level folder of the project, but  full path too in different sections like with diagnostics
![image](https://user-images.githubusercontent.com/48126993/115994129-5efe9f00-a5de-11eb-9224-e9bb7a1e2237.png)

And sometimes your project root directory names like src. Features to set project name/rename project would be nice too 

now i create such map to just edit txt file
```
local path_to_projectile = vim.fn.stdpath('data')..'/telescope-projects.txt' 

  p = {
      name = '+Projects'                                                 ,
      o = {':e '..path_to_projectile..'<CR>' , 'open file'} ,
      s = {':lua require"telescope".extensions.project.project{}<CR>'    , 'projectile'} ,

```
With these features i think this could be near to emacs projectile coolness

**Comment by claidler** [comment]
Yes renaming projects would be good, I'll look into that one. I'm not entirely sure what you mean here - "It would be cool to see not only top level folder of the project, but full path too in different sections like with diagnostics".
You'd like to be able to add different folders within a project also?

**Comment by artofnothingness** [comment]
I meant that when you search for a project, you only see the name of the project (by default, this is the top-level folder). It would be great if when you search for a project in telescope window, both the name of the project and the path to it are displayed.  Or may be only just full path like in doom-emacs projectile 
![image](https://user-images.githubusercontent.com/48126993/116811063-f1a7bc80-ab4f-11eb-985a-213eab502d9f.png)

**Comment by claidler** [comment]
Ah okay thanks @artofnothingness that should be a pretty simple addition. I'll look into this one

**Comment by claidler** [comment]
@artofnothingness I've made a change for this one here - https://github.com/nvim-telescope/telescope-project.nvim/compare/master...feature/display-path but I'm not sure it's what everyone will want, so just holding back from merging for the time being, as it might be something worth considering as an option, rather than a default setting

**Comment by artofnothingness** [comment]
@claidler 
That's nice! Renamings works too. 
For me these features very useful. Thanks!

**Comment by claidler** [comment]
No probs @artofnothingness I've updated the master branch now, with config options for this - which you can find in the readme. I'm going to close this now, but let me know if you come across any issues :+1:

**Comment by venzen** [comment]
@claidler  The addition of the `display_type` option makes the picker more useful for me. Is there a way to apply the `"full"` option to all instances of the project picker? e.g. when calling `:Telescope project`
