### ISSUE TITLE
Loading extension clears telescope config

### ISSUE THREAD

**Issue by YaBoiBurner** [nvim-telescope/telescope-project.nvim#26]
Problem code: https://github.com/nvim-telescope/telescope-project.nvim/blob/master/lua/telescope/_extensions/project.lua#L16
```lua
require('telescope').setup {}
```
Function it's calling: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/init.lua#L28-L41
```lua
--- Setup function to be run by user. Configures the defaults, extensions
--- and other aspects of telescope.
---@param opts table: Configuration opts. Keys: defaults, extensions
---@eval { ["description"] = require('telescope').__format_setup_keys() }
function telescope.setup(opts)
  opts = opts or {}
  -- irrelevant code omitted
  require('telescope.config').set_defaults(opts.defaults)
  _extensions.set_config(opts.extensions)
end
```

`telescope.setup` is supposed to be called by the user, instead of by plugins.
Calling it *at all* will clear the user's telescope config at that point.

Additionally, while this doesn't really matter yet, calling `telescope.setup` before `telescope.register_extension` should render this plugin unconfigurable in the future.

I have no idea why it's even called, but the only way a user can work around it right now is to load this extension, then run `telescope.setup` with their own config (since this extension's call does nothing), and then load any other extensions.

**Comment by claidler** [comment]
@YaBoiBurner makes sense, thanks for bringing this up. I copied under advice from another extension as a template, so just want to clarify with @Conni2461 that it's okay to remove this, as he knows a lot more than me about Telescope.

**Comment by Conni2461** [comment]
From which extension did you copy it? Also I checked my original review and i said you should not call `setup`, because i wasn't sure what happens.
https://github.com/nvim-telescope/telescope-project.nvim/pull/1#discussion_r547332656

I would remove it

**Comment by claidler** [comment]
@Conni2461 hmm, weird that I would have put that in for no reason. Good point. I'll remove it. I used the vimspector extension as  a template, so it possibly came from there. Otherwise no idea where it came from!

**Comment by claidler** [comment]
I've remove this and pushed straight to master
