### ISSUE TITLE
Show project path

### ISSUE THREAD

**Issue by kdurant** [nvim-telescope/telescope-project.nvim#33]
When entering the command `:Telescope project`, the full path of the project is displayed

**Comment by garwil** [comment]
On the current version `display_type` defaults to `minimal`, which doesn't show the full project path.

Doing this `lua require'telescope'.extensions.project.project{ display_type = 'full' }` or `:Telescope project display_type=full` will show the full path of the project.

Setting `display_type` to `minimal` in either of those examples will only show the project name.

**Comment by claidler** [comment]
I'm going to close this one. Thanks @garwil
