### ISSUE TITLE
Issues with project scanner

### ISSUE THREAD

**Issue by TheBlob42** [nvim-telescope/telescope-project.nvim#35]
After updating `telescope` and  `telescope-project` the latest version today I was keen to try the new project scanning feature implemented in #34. Unfortunately I encountered the following two issues:
- I need to create `/tmp/found_projects.txt` file by hand or otherwise I experience the following error on startup. I would prefer if this file would either be created automatically or if there was at least a note in the `readme` :slightly_smiling_face: 
```text
E5113: Error while calling lua chunk: ...e-project.nvim/lua/telescope/_extensions/project/git.lua:28: bad argument #1 t
o 'lines' (/tmp/found_projects.txt: No such file or directory)
```
- After "fixing" the above I still see the following error when trying to execute `:Telescope project<CR>`. Seems like you just need to update the plenary function call.
```text
E5108: Error executing lua ...pack/packer/start/telescope.nvim/lua/telescope/utils.lua:381: strdisplaywidth deprecated.
 please use plenary.strings.strdisplaywidth
```

Otherwise great plugin that eases my daily work by a lot :+1:

**Comment by gfsd3v** [comment]
Went to the same process a few hours ago, let me know if you guys need some more infos.

**Comment by harrygallagher4** [comment]
I just manually created `/tmp/found_projects.txt` and it's working fine now.

**Comment by harrygallagher4** [comment]
My pull request fixes both of these errors and another issue I ran into after fixing them.

**Comment by pidgeon777** [comment]
I also have this problem.

**Comment by Conni2461** [comment]
second issue was on me because we moved util functions from telescope to plenary to make them more accessible.

**Comment by ranjithshegde** [comment]
@Conni2461  I am not entirely sure if this is related. I had the same errors as above, and now with the fix I have this

`E5108: Error executing lua ...oject.nvim/lua/telescope/_extensions/project/finders.lua:10: attempt to index local 'opts' (a nil value)
`
