### ISSUE TITLE
Customise default keys

### ISSUE THREAD

**Issue by garwil** [nvim-telescope/telescope-project.nvim#39]
This is probably just my lack of understanding of how Telescope works, but is there a way to customise the default keys?

I currently have my Telescope set up with `<Esc>` bound to close in Insert mode, and I just bind `<C-whatever>` to what ever I want to do. This is fine for the other builtins/extensions that I use, but means that I can't use telescope-project, since all the bindings are for Normal mode.

**Comment by claidler** [comment]
@garwil I'll create insert mode mappings, which are basically the same as the normal mode mappings but using <C-whatever>, hopefully that will resolve things for you?

**Comment by garwil** [comment]
Yeah, that'd be awesome, thanks!

**Comment by claidler** [comment]
Should be updated now @garwil I've update the readme, only difference is that m is used for rename, rather than r

**Comment by garwil** [comment]
I've just tested it out, it works brilliantly, thanks!

I'm just starting to learn a bit of Lua, I'd be interested to try to figure out how to pass the key mappings in from the Telescope config. If I do I'll submit a PR!

**Comment by claidler** [comment]
Thanks @garwil that'd be great. This plugin is my only experience with lua
