### ISSUE TITLE
Mapping for selecting project

### ISSUE THREAD

**Issue by koopa1338** [nvim-telescope/telescope-project.nvim#42]
The mappings in general are pretty convenient but I think it is confusing that `<CR>` is not changing to the work directory of the project but instead calls the rename action that already has a mapping.

The title of the popup clearly says `Select a Project` what imo means switching to that project context. My suggestion is to also map `<CR>` to change to the working directory of the selected project as the main goal of this extension to me is quick project switching.

**Comment by claidler** [comment]
@koopa1338 `<CR>` is mapped to find files within the project and should also change the working directory. It shouldn't be set to rename the project. I'll double check later to make sure a recent update hasn't caused a problem with this.

**Comment by claidler** [comment]
Ah yeah it's an unwanted side effect of a recent update. It only occurs in insert mode. I'll look to fix this later on. Thanks for bringing it to my attention

**Comment by claidler** [comment]
actually I've pushed a quick fix for this as I think it's a pretty major issue. Thanks again @koopa1338 should be resolved on an update
