### ISSUE TITLE
Add multiple base_dir directories

### ISSUE THREAD

**Issue by karb94** [nvim-telescope/telescope-project.nvim#45]
I started to use this plugin and it's very useful. Great work!

One thing I'm missing is the ability to add multiple directories (base_dirs) where to look for projects. My personal and work projects are not under the same directory so I would like to pass a list (table) to base_dir instead of a string. Can this be done at the moment or any plan to implement it?

**Comment by claidler** [comment]
That's a good point @karb94. Unfortunately you'll have to add projects outside of the base_dir, manually at the moment, but this is definitely a feature we should look into. I'll make a note of it. Thanks

**Comment by karb94** [comment]
Thanks @claidler, good to hear this will be added at some point.

I was looking at the code and I saw that projects are stored in `telescope-projects.txt` so I could manually add additional projects there. But this left me wondering why is it necessary to store the list of projects in a text file? If the use case is to add extra projects manually I would expect to add them through the extension config not a text file. Maybe I'm missing something as I'm not familiar with this project.

Also as a result of using `telescope-projects.txt` to store a list of projects when I changed the `base_dir` in the extension config the previously added projects in `telescope-projects.txt` remain there. This was very useful for my use case but it looks to me as an undesired behaviour. If you change your `base_dir` you probably don't want the projects of the old `base_dir` directory hanging around.

**Comment by claidler** [comment]
@karb94 when I said 'manually add projects', I meant using the default key mappings - go to a folder in your terminal, open neovim, open telescope-projects with ctrl+p (or whatever you've mapped it to), then enter normal mode and press 'c' (or ctrl+a from insert mode) to add a project - if you're inside a git repo, this will add the root directory as a project, if you're not it just adds the current directory.  There are key mappings for deleting projects and renaming projects also. 

The base_dir feature was added fairly recently by another user (much appreciated work and a really useful feature). It's another way of getting your projects listed. 

I'm not sure if we should delete the projects automatically when a user changes the base_dir. Your usage of telescope-project, as fine as it is, is not how I was originally intending people to use it. 

I like the idea to extend this base_dir feature, to allow multiple directories, but I'd feel uncomfortable with deleting peoples projects.

The text file will allow us to add workspaces and other features in the future. It's a way of us having a database type storage, without any dependencies.

**Comment by karb94** [comment]
Hey @claidler thanks a lot for the detailed answer. It turns out I completely missed the point on how the extension is designed to work so thank you for the explanation. I see now that base_dir is more of an additional way of adding projects no the main one as I originally thought. Everything makes sense now!

**Comment by claidler** [comment]
Hi @karb94 this has been implemented now by another user. The readme has been updated  so please have a look there as and you will need to change your config slightly.
