### ISSUE TITLE
[Question] project.nvim for logic?

### ISSUE THREAD

**Issue by oskarskog** [nvim-telescope/telescope-project.nvim#49]
Hello there and thanks for this project, it helped me move back to nvim from emacs. 

As I was looking at the roadmap I started wondering whether it would make sense to separate concerns a bit by creating a library, something like a project.nvim, which would provide all the business logic for managing projects as well as functioning as an API for interacting with the project file. This is pretty much what's in [this](https://github.com/nvim-telescope/telescope-project.nvim/projects/3#card-63777022) card. To my knowledge there is currently no such project managing library, but perhaps one should be created?

The benefits from this approach would imo. be that:
1. users of different fuzzy search (or whatever) library/framework could benefit from the logic project 
2. chances of having more people contribute is larger if the project is less opinionated 
3. perhaps we will end up with one very stable lib instead of many not so stable 

This is, I think, how it works in the emacs community, more or less. There's a projectile library that provides the project managing logic and then a bunch of fuzzy matching frameworks etc. providing different UIs and functionality on top of that.

Any thoughts?

**Comment by oskarskog** [comment]
This vcs/project base library seems to be what is discussed here https://github.com/nvim-lua/wishlist/issues/6

**Comment by claidler** [comment]
@oskarskog that's a really interesting idea. I like it a lot.

**Comment by claidler** [comment]
It didn't make sense initially but as  it's grown, it makes much more sense

**Comment by claidler** [comment]
I'm going to add this to the roadmap
