### ISSUE TITLE
[Question] all git subdirs are not automatically added

### ISSUE THREAD

**Issue by dhananjaylatkar** [nvim-telescope/telescope-project.nvim#50]
Hello,

I added these lines in config - 
```lua
require('telescope').setup {
	extensions = {
		project = {
			base_dir = '~/code',
			max_depth = 3
		}
	}
}
```
I was expecting it to add all git directories under `~/code` in project list but, nothing is happening. I don't want to add all directories manually as there are lots of them. Is there a way to solve this?

**Comment by claidler** [comment]
@dhananjaylatkar can you confirm what OS you're using?

**Comment by dhananjaylatkar** [comment]
@claidler I'm on macOS.
I also noticed that `find` command used in code is throwing an error.
```shell
❯ find ~/code -maxdepth 3 -type d -name .git -printf '%h\n'
find: -printf: unknown primary or operator
```

**Comment by claidler** [comment]
Ah yeah thanks @dhananjaylatkar I'm going to have a look at a PR this morning that should fix this. I'm on Linux, seems to be a Mac OS specific issue

**Comment by claidler** [comment]
Okay @dhananjaylatkar it could be working now? I can't actually check as I don't have MacOS. Could you let me know either way?

**Comment by dhananjaylatkar** [comment]
Hi @claidler,
Projects are not getting added. Do I have to execute any command to start listing git directories? 
I don't think it's executing `git.update_git_repos()` function since `/tmp/found_projects.txt` is not present on my device. 
Is my config correct?

**Comment by claidler** [comment]
@dhananjaylatkar the `require('telescope').load_extension('project')` line needs to be after `require('telescope').setup`

Is that the issue? Something I noticed which was causing a problem for me. 

Are you still getting the error message? If so, then just make sure you've updated the plugin also?

**Comment by dhananjaylatkar** [comment]
> the `require('telescope').load_extension('project')` line needs to be after `require('telescope').setup`

That was it. Thanks!!

**Comment by claidler** [comment]
Hi @dhananjaylatkar, just a heads up - a multiple base dirs feature has been added by another user. The readme has been updated, please have a look there as and you will need to change your config slightly.
