### ISSUE TITLE
Use Telescope `cwd` to project names

### ISSUE THREAD

**Issue by vlcinsky** [nvim-telescope/telescope-project.nvim#54]
Telescope supports parameter `cwd`.

Current `telescope-project.nvim` does not use this paramter.

# Proposal

Use value of `cwd` to limit list of projects only to those, which start with given directory.

# Example
I have projects organized in folders:
- `~/sandbox`
- `~/devel/tis`
- `~/devel/ttr`

If `cwd=~/sandbox`, only projects from this folder and subfolders shall be shown

If `cwd=~/devel/tis`, only projects from here shall be shown.

If `cwd=~/devel`, only projects from any subdirectory of `~/devel` shall be presented.

**Comment by claidler** [comment]
@vlcinsky have you tried the base_dirs option in the readme for this? It adds all of the projects in specific folders automatically and will add any new ones that get added by scanning the base_dirs each time it opens

**Comment by vlcinsky** [comment]
@claidler yes I tried and it was actually motivation for this idea.

I tried to configure base_dirs - I like the concept, but for some internal reasons (fighting with LunarVim configs on my machine) it failed. But I managed to generate the  `~/.local/share/nvim/telescope-projects.txt` manually (using small python utility)  and it has 205 items. For this reason I would invite an option to filter the items using e.g. `cwd`.

Another options:
- filter per base_dir (I am not aware of this option)
- use the workspaces (which seem to be prepared)

**Comment by claidler** [comment]
Workspaces is a feature in progress, but not ready yet. It will allow you to filter your projects by applying them to certain workspaces.

It seems like the main problem here is that base_dirs isn't working for you. If it was working, I don't imagine you'd require this? I could be wrong, but it's not a feature I'd imagine the majority of people would care for. 

Something I've recently realised is that the require('telescope').load_extension('project') line in your config needs to be after require('telescope').setup. I wonder if this is the problem you're having with base_dirs not working?

**Comment by vlcinsky** [comment]
I have managed to run the project telescope with base_dirs configuration and it nicely and very quickly finds all the projects in given directories.

Anyway, my problem is, that I have a lot of projects - 205 at the moment.

As they are grouped per client, I would appreciate to filter these somehow, e.g. by root client project directory

Alternative option is to prefix project names with names from `base_dirs`. This way it is easy to filter by base_dir names first and then continue with filtering names from that group.

Indexing projects (using my python tool) generates lines as follows:
```
~/sandbox dany=/home/javl/sandbox/discord/dany=1
~/sandbox rg-test=/home/javl/sandbox/rg-test=1
~/sandbox one=/home/javl/sandbox/pycharm/one=1
~/devel/tis dpo-magnetky-install=/home/javl/devel/tis/_archive/dpo-magnetky-install=1
~/devel/tis dpo-magnetky-src=/home/javl/devel/tis/_archive/dpo-magnetky-src=1
```
As filtering is ignoring full path, but takes into account project name - with the prefix I have easy chance to filter per client.

**Comment by claidler** [comment]
@vlcinsky ah I see. This can be part of the workspaces feature I'm adding. Add entire directories to a workspace. I'll put it on the roadmap

**Comment by vlcinsky** [comment]
@claidler very quick solution to my needs is to us full path (possibly normalized) as project title.

This way (as filter works on project titles) one can filter by directory part too, e.g. using `devtisdpoinst` to pick `dpo-magnetky-install` from `~/devel/tis/_archive` directory.

Even better would be to put a space between (workspace) directory and project name as it allows to filter using project name if space is the first filter character, e.g. using `<space>dpoinst`

**Comment by mandarvaze** [comment]
@vlcinsky I'm trying to use this with LunarVim. Since you mentioned you are also using LunarVim, and that you were able to get it to work, can you share your config ? More importantly where does the config go ? (which file?) I'm new to LunarVim and still getting used to.
