### ISSUE TITLE
Search across projects?

### ISSUE THREAD

**Issue by reflog** [nvim-telescope/telescope-project.nvim#56]
Hi! First of all - amazing plugin, thanks for your work!
I was wondering, how hard would it be to implement 'search across projects', either for file or text?

**Comment by claidler** [comment]
Thanks @reflog 😊 searching across multiple projects is a great idea. I think that should be part of workspaces which is currently WIP. I'll add it to the roadmap. Workspaces will allow people to add multiple projects to a 'workspace', then people could potentially search across a workspace. I'm not sure how difficult this would be, but will discuss with the telescope guys to find out how/if we could implement this.

**Comment by reflog** [comment]
That sounds great 👍
