### ISSUE TITLE
Error in packer_compiled: ...project.nvim/lua/telescope/_extensions/project/utils.lua:68: attempt to call method 'match' (a nil value)

### ISSUE THREAD

**Issue by karb94** [nvim-telescope/telescope-project.nvim#58]
I get
```
Error in packer_compiled: ...project.nvim/lua/telescope/_extensions/project/utils.lua:68: attempt to call method 'match' (a nil value)
```
with this config:
```Lua
require("telescope").setup({
  extensions = {
    project = {
      base_dirs = {
        {vim.env.HOME .. "/projects", max_depth=2},
      }
    }
  }
})
```
I don't know if my config is wrong but the error appears because the `get_project_from_path` function from `_extensions/project/utils` is being passed a `table` instead of a `string` for some reason. This error can be solved by changing `_extensions/project/utils.lua:68` to:
```Lua
local title = path.filename:match("[^/]+$")
```

**Comment by jens1205** [comment]
PR https://github.com/nvim-telescope/telescope-project.nvim/pull/59 fixes this issue

**Comment by karb94** [comment]
Thank you @jens1205 for your PRs. The print statements were driving me crazy and I didn't know where they were coming from. With both PRs everything works like it's supposed to so hopefully they get merged soon

**Comment by claidler** [comment]
Thanks @jens1205 I'm very happy to merge this once the plenary merge is complete

**Comment by Conni2461** [comment]
Merged the pr that fixed that issue. Closing for now
