### ISSUE TITLE
Feature Request: Equivalent of `:lcd path_to_project` and "no(l)cd" (improve documentation)

### ISSUE THREAD

**Issue by matu3ba** [nvim-telescope/telescope-project.nvim#61]
1. The behavior of how `cwd` is changed is underspecified. Neovim offers 1. `:cd` and 2. `:lcd` to change paths. But one could also think of 3. not changing the path for only opening the file [ie to compare stuff].
2. I think even changing the default to `:lcd` would be more optimal, to run things in the script or `:e pathtofile` on the correct project folder

**use cases**
- My [simple project for using associated script folders](https://github.com/matu3ba/telescope-project-scripts.nvim) I am frequently looking and copy your code to modify it. Having `PATH` cluttered makes this annoying for quick lookups.
- My project intends to make script running usable from the git root of the project. Its very unnatural to have `cwd` not being set to the project git root, when one wants to run quick scripts or modifies stuff etc.
- In future I want to make PATH navigation possible (in neovim and shell associated to project) to get restricted to a local project scope. Having correct `cwd` set is a basic building block for that.

I have also some other remarks on the structure of the project to make re-usage simpler,
but this is not imminent. Thanks for the plugin and let me know what you think on this.

**Comment by l4zygreed** [comment]
yeah, I think it's better to add option to choose between `cd`, `lcd`, `tcd` and no cd

I don't like that plugin `cd` whole nvim to selected folder

**Comment by tiagovla** [comment]
I also wanted something like ``lcd`` but for a buffer scope instead of a window scope. Just an idea:

```lua
local M = {}
local history = {}

vim.api.nvim_exec(
    [[
      augroup TrackCWD
        autocmd!
        autocmd BufEnter * lua require"thisfilepath".on_enter()
        autocmd BufLeave * lua require"thisfilepath".on_leave()
      augroup end
    ]],
    false
)

function M.on_enter()
    local buf = vim.api.nvim_get_current_buf()

    if not vim.api.nvim_buf_get_option(buf, "buflisted") then
        return
    end

    local last_path = history[buf]
    if last_path then
        vim.fn.execute("cd " .. last_path, "silent")
        -- require("nvim-tree").change_dir(last_path) --update nvimtree
    end
end

function M.on_leave()
    local buf = vim.api.nvim_get_current_buf()

    if not vim.api.nvim_buf_get_option(buf, "buflisted") then
        return
    end

    history[buf] =  vim.fn.getcwd(-1, -1)
end

return M
```

**Comment by matu3ba** [comment]
> buffer scope instead of a window scope

Please try to explain your use case in [harpoon](https://github.com/ThePrimeagen/harpoon), since the plugin is more tailored to buffer navigation.

**Comment by maxmahlke** [comment]
+1 for having an option to choose between `:cd` and `:lcd`, I like to have one tab per project and using `cd` when switching to another project in a new tab messes up the paths in all other project tabs.

**Comment by l4zygreed** [comment]
still no updates to this issue? seems like it's [time to learn lua](https://youtu.be/EzWNBmjyv7Y?t=7)

**Comment by rizkifuad** [comment]
changing this [line](https://github.com/nvim-telescope/telescope-project.nvim/blob/4658d78523a5a005af80243f1d0b4e7e2a118dae/lua/telescope/_extensions/project/utils.lua#L122) here to `lcd` works for me for the time being

**Comment by ccakes** [comment]
Check MR #103 which resolves this at least for me

**Comment by dpetka2001** [comment]
Any progress on this? Does the suggested PR solve the problem? It's really annoying that it changes the global `cwd` and not just the buffer `cwd` or tab `cwd` if you choose to open the file in a new tab. Also could we stop the behavior by just selecting the project to also change `cwd`. Many times I may cancel the command but `cwd` is already changed. Preferably it could change after selecting a file to open?
