### ISSUE TITLE
Python: Activate virtualenv in the project folder

### ISSUE THREAD

**Issue by quantum-booty** [nvim-telescope/telescope-project.nvim#68]
Sometimes in the project there is a venv folder or a .python-version file that specifies the virtualenv to be used. Is there a way of activating the virtual env when I jump to a project via Telescope projects? Otherwise this kinda defeats the purpose because I'd have to manually cd into the project directory, activate the virtual env then open nvim.

**Comment by matu3ba** [comment]
Usually sourcing the lspconfig or whatever actives your venv should do this for you. The problem with lua is that you need to clear the cache and then require the according file for that.

**Comment by SirSilver** [comment]
You can force nvim to set $VIRTUAL_ENV for you on workspace changing, but also you need to add virtual env bin directory to $PATH.

For pipenv and poetry I use:
```
local lspconfig = require"lspconfig"
local util = require('lspconfig/util')
local path = util.path

local function get_pipenv_dir()
    return vim.fn.trim(vim.fn.system('PIPENV_PIPFILE=Pipfile pipenv --venv'))
end

local function get_poetry_dir()
    return vim.fn.trim(vim.fn.system('poetry env info -p'))
end

local function get_python_dir(workspace)
    local pipenv_match = vim.fn.glob(path.join(workspace, 'Pipfile'))
    if pipenv_match ~= '' then
        return get_pipenv_dir()
    end

    local poetry_match = vim.fn.glob(path.join(workspace, 'poetry.lock'))
    if poetry_match ~= '' then
        return get_poetry_dir()
    end
end

local function setup_virtual_env(workspace)
    local old_venv = vim.env.VIRTUAL_ENV
    vim.env.VIRTUAL_ENV = nil
    local venv = get_python_dir(new_root_dir)

    if (not venv and old_venv) or (venv == old_venv) then
        vim.env.VIRTUAL_ENV = old_venv
        return
    end

    vim.env.VIRTUAL_ENV = venv

    if old_venv then
        vim.env.PATH = vim.env.PATH:gsub("^(.-)/bin", path.join(venv, "/bin"))
    else
        vim.env.PATH = path.join(venv, "/bin:", vim.env.PATH)
    end
end

lspconfig.pyright.setup{
    on_attach = on_attach,
    capabilities = capabilities,
    on_new_config = function(new_config, new_root_dir)
        setup_virtual_env(new_root_dir)
    end
}
```

This also works for pylsp, but this will not work if you manipulate $PATH somewhere else, because on every virtual env changing it deletes first entry to $PATH and replace it with venv bin dir.

There might be other solutions like executing venv activating scripts, but I have never tried it.

**Comment by quantum-booty** [comment]
Solved with this implementation:
https://github.com/quantum-booty/nvim/commit/3498b61354c199624c974d41cbac18ba95d0c7f0
