### ISSUE TITLE
E523: Not allowed here.

### ISSUE THREAD

**Issue by jkary** [nvim-telescope/telescope-project.nvim#71]
Hello,

I am consistently able to reproduce the above error.  I'm not sure if I have a bad config or missing dependency.

OS: macOS Big Sur 11.5.2

Running NeoVIM version: 

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info

If I perform the following:
1. \# vim .
1. \<CTRL-p\>  (Open project)
2. type 'mas' (for master branch)
3. backspace 3 chars to remove ('mas' from the window, it does not go away from the previous screen)
4. type 'main' (for selecting main.tf)
5. jjj (down 3 lines, not sure if this is significant)
6. i (try to insert text) --- E523: Not allowed here

At this point I am unable to enter insert mode no matter what file I pick.  I have to restart nvim to reset the state.

[vimrc.txt](https://github.com/nvim-telescope/telescope-project.nvim/files/7418601/vimrc.txt)

**Comment by matu3ba** [comment]
Sorry, but this is a too big config. Can you bisect to a minimal plugin config?
Its easier to use git for this, ie with dotfiles. You could use [my dotfile skeleton](https://github.com/matu3ba/dotfiles_skeleton) for this.

**Comment by jkary** [comment]
Hi there,

Sure.  I will update this issue once I narrow it down.

Jason

**Comment by jkary** [comment]
Ok.  So this plugin seems to be causing the issue.

https://github.com/Shougo/deoplete.nvim

Can you confirm?

**Comment by matu3ba** [comment]
> Can you confirm?

Can you provide a minimal init.vim, so I can try it?

**Comment by jkary** [comment]
Good Day,

Please find the minimal .vimrc file attached
[vimrc-broken.txt](https://github.com/nvim-telescope/telescope-project.nvim/files/7528520/vimrc-broken.txt)

Thanks
Jason

**Comment by matu3ba** [comment]
> type 'main' (for selecting main.tf)
jjj (down 3 lines, not sure if this is significant)
i (try to insert text) --- E523: Not allowed here

Your instructions are incomplete or not logically consistent to me:

1. The first pick of the project with backspace deletes the text in the insertion window, so there is nothing to delete.
2. jjj would insert 3 j's. Did you escape to leave insertion mode?
3. Or did you hit the second time backspace to open the file main.tf?
4. Does the error not occur once you remove deplete? 
5. I suspect `expr` or `noremap` breaking stuff as motivated [here](https://stackoverflow.com/a/59441479). Would not be the first time that plugins with default mappings have weird effects.
