### ISSUE TITLE
Creating a project in a git dir

### ISSUE THREAD

**Issue by ssipos90** [nvim-telescope/telescope-project.nvim#78]
Hello,

Where I work, our 3-part product is in a single git repo and I'd like to create different projects for each one, but when I create, it selects the git repo. How can I disable using the git repo as the project root?

Thanks

**Comment by matu3ba** [comment]
This is planned to be added after the refactor for #75.
In the meantime, edit your `.local/share/nvim/telescope-project.txt`.
Please make a backup before every change.

**Comment by ssipos90** [comment]
Gracias
