### ISSUE TITLE
It doesn't work on windows

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-telescope/telescope-project.nvim#83]
```
    projects = {
        base_dirs = {
            '$APPDATA/Local/nvim/'
        },
        hidden_files = true
    }
```
![image](https://user-images.githubusercontent.com/92417638/145511240-8f09c83a-d862-4df8-9c9e-87590113f116.png)
this is strange

**Comment by tristone13th** [comment]
project not projects

**Comment by bryant-the-coder** [comment]
still cant...

**Comment by tristone13th** [comment]
> still cant...

Maybe you should try expanding the $APPDATA yourself?

**Comment by bryant-the-coder** [comment]
O.o

**Comment by bryant-the-coder** [comment]
can i lazyload it??

**Comment by tristone13th** [comment]
> can i lazyload it??

I think it depends on which plugin manager you are using, as far as I know, Packer.nvim can lazy load any plugins when a specific event occurs.

**Comment by bryant-the-coder** [comment]
how? i m using packer

**Comment by tristone13th** [comment]
> how? i m using packer

Check the README, it has a lot of demonstrations, basically put the plugins under opt rather than start then load it when need.

**Comment by bryant-the-coder** [comment]
i mean for this plugin...

**Comment by dhananjaylatkar** [comment]
> i mean for this plugin...

It's late but you can refer to this - https://github.com/dhananjaylatkar/dotfiles/blob/master/nvim/.config/nvim/lua/plugins.lua#L60=
