### ISSUE TITLE
Starting nvim with telescope project doesn't properly  show the file picker after choosing a project

### ISSUE THREAD

**Issue by hahuang65** [nvim-telescope/telescope-project.nvim#85]
If you start nvim like so: 

```
nvim -c ":lua require'telescope'.extensions.project.project{}"
```

The project picker looks fine:
![grim_01_06_22-21_16_51](https://user-images.githubusercontent.com/280972/148495603-b0baf4cd-5804-4df8-8adb-bdc5b40082a0.png)

But once you pick project, the file picker is busted:
![grim_01_06_22-21_17_05](https://user-images.githubusercontent.com/280972/148495632-3eb7a212-46b0-49ca-b1ab-c09d9308ea8d.png)

But you are able to type:
![grim_01_06_22-21_17_21](https://user-images.githubusercontent.com/280972/148495654-8b48ab25-3cd7-426b-9b4f-61be9c6d7e46.png)

and if you type something that can be picked, it can be opened.

**Comment by alerque** [comment]
I am unable to replicate this. Launching neovim like that works just fine for me and the file picker comes up and works fine after I pick a project.

Neovim 0.7.2 here, current HEAD of telescope and telescope.project.
