### ISSUE TITLE
Suggestion: add mapping to just change cwd

### ISSUE THREAD

**Issue by pwntester** [nvim-telescope/telescope-project.nvim#9]
Like using `g(o)` to do `:cd <project root>`

**Comment by cjjlaidler** [comment]
@pwntester I'm sorry, I don't quite follow. It may just be me. Could you please explain a bit further?

**Comment by pwntester** [comment]
I use you plugin (great one BTW) to quickly open files from other projects. But I have a use case where I dont want to open any particular file, I just want to change Neovim cwd for other commands to work.
My specific use case is when I open a GitHub Pull Request from [Octo.nvim](https://github.com/pwntester/octo.nvim). If I want to see the PR review comments I need to do `:Octo pr reviews` but this command requires to have the CWD pointing to the directory where the repo the PR refers to is checked out. Currently I use telescope project to open a file of that given repo/project (which will set the right CWD) and then go back to the octo buffer to issue the `Octo pr reviews` command. I would be great if I could skip opening an arbitrary file from that project.

**Comment by cjjlaidler** [comment]
Thanks @pwntester 😊 I see what you're saying. Yes, no probs, I'll add this feature. I can see that it'll be useful.

**Comment by cjjlaidler** [comment]
I've added this in. Just need to test it later tonight and then will merge.

https://github.com/nvim-telescope/telescope-project.nvim/pull/10

**Comment by pwntester** [comment]
Awesome thanks!

**Comment by cjjlaidler** [comment]
@pwntester not quite there, had to revert it. I'll get onto this soon. Shouldn't take long, but I have a lot on at the moment unfortunately!

**Comment by claidler** [comment]
Hmm this one is proving trickier than I thought. It seems whenever telescope closes, the working directory is reverted to whatever directory you get left in. @Conni2461  do you have any idea how I could do this? 

I was looking at something like this:
`project_actions.change_working_directory = function(prompt_bufnr)
  local dir = actions.get_selected_entry(prompt_bufnr).value
  vim.fn.execute("cd " .. dir, "silent")
  actions.close(prompt_bufnr)
end
`
I imagine the above code changes the directory and then when telescope closes, changes the directory again to whatever directory it puts you in on close. This has made me question a previous PR I approved also - which is good I guess!

**Comment by Conni2461** [comment]
I have put that into a scratch file that i had lying around :laughing: 
```lua
local action_state = require("telescope.actions.state")
local actions = require("telescope.actions")
local finders = require("telescope.finders")
local pickers = require("telescope.pickers")
local conf = require("telescope.config").values
local make_entry = require('telescope.make_entry')

local scan = require("plenary.scandir")

local results = scan.scan_dir('.', {
  add_dirs = true,
  depth = 1,
})

pickers.new({}, {
  prompt_title = 'Find Files',
  finder = finders.new_table {
    results = results,
    entry_maker = make_entry.gen_from_file({}),
  },
  previewer = conf.file_previewer({}),
  sorter = conf.file_sorter({}),
  attach_mappings = function(prompt_bufnr)
    actions.select_default:replace(function()
      actions.close(prompt_bufnr)
      local dir = action_state.get_selected_entry(prompt_bufnr).value
      vim.fn.execute("cd " .. dir, "silent")
      print(vim.loop.cwd(), vim.fn.getcwd())
    end)
    return true
  end
}):find()
```
And it seems to work. Run with `:luafile %` Am i missing something

**Comment by claidler** [comment]
Thanks @Conni2461 I can see you're doing 'cd' after actions.close, so that may be where I'm going wrong 😊

**Comment by claidler** [comment]
Sorry this took a while @pwntester. It should be with you in the latest update, just hit 'w' on the project. I updated the readme.

**Comment by claidler** [comment]
I'm going to close this, but let me know if you have any issues!

**Comment by pwntester** [comment]
Awesome! Thanks!
